### ISSUE TITLE
AssertionError: Data path not found.

### ISSUE THREAD

**Issue by Rakiba291** [joelouismarino/amortized-variational-filtering#2]
Hi there,

Thanks for the useful repo. I was trying to clone the repo and run by your experimental data. However, I am getting an error of Data path not found. I tried different dataset you have provided in the code such as, Nottingham but none of the dataset is downloaded  to train. I am attaching the error I am getting as well.  Could you please let me know how to fix it? Thanks in advance

![image](https://user-images.githubusercontent.com/46694769/89721764-6de0eb00-d996-11ea-9129-16f404aea389.png)

**Comment by joelouismarino** [comment]
Hi @Rakiba291. You're running into the assert on Line 20 in `load_dataset.py`. This is just to make sure that you've properly set the path to where you'd like to automatically download the data. If you look in `config/data_config.py`, you should see an entry labeled `'data_path'`. Make sure that this is a valid path. Let me know if you run into any issues.

**Comment by Rakiba291** [comment]
Hi,
 
Thanks for your response. I am now able to download the data. However, I ran into another problem and it seems that I could not solve this issue with other PyTorch references. I am attaching the error snippet. I was using the kth dataset to obtain the results. 

----------------------------------
Putting the model on the GPU...
Iteration: 1 of 48
C:\amortized-variational-filtering-master\lib\modules\latent_variables\fully_connected.py:210: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  grad.volatile = False
Traceback (most recent call last):
  File "train.py", line 85, in <module>
    start_training(run_config, train_config, data_config, model_config)
  File "train.py", line 44, in start_training
    out = train(train_data, model, optimizers, train_config, data_config)
  File "C:\amortized-variational-filtering-master\util\train_val.py", line 14, in train
    return run(data, model, train_config, data_config, optimizers=optimizers)
  File "C:\amortized-variational-filtering-master\util\train_val.py", line 238, in run
    model.step()
  File "C:\amortized-variational-filtering-master\lib\models\svg.py", line 380, in step
    self._gen_input = self.prior_lstm(self._prev_h.unsqueeze(1), detach=False)
  File "C:\Anaconda3\envs\ret\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\amortized-variational-filtering-master\lib\modules\networks\lstm.py", line 62, in forward
    layer_output = layer(input, detach)
  File "C:\Anaconda3\envs\ret\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\amortized-variational-filtering-master\lib\modules\layers\lstm.py", line 49, in forward
    self._hidden_state, self._cell_state = self.lstm.forward(input, (hs, cs))
  File "C:\Anaconda3\envs\ret\lib\site-packages\torch\nn\modules\rnn.py", line 936, in forward
    self.check_forward_input(input)
  File "C:\Anaconda3\envs\ret\lib\site-packages\torch\nn\modules\rnn.py", line 762, in check_forward_input
    input.size(1), self.input_size))
RuntimeError: input has inconsistent input_size: got 1, expected 128
------------
I am using pytorch 1.3.0 and Cuda 9.2. 

Please let me know if you can help me to fix it. Thanks again.

**Comment by joelouismarino** [comment]
Hi @Rakiba291, it looks like the first error is due to the PyTorch version. The code was written with PyTorch version `0.3.0.post4`, which is now quite old. When I have some time, I'll look into updating the code to the latest version of PyTorch. In the meantime, if you use version `0.3.0.post4`, do you still get the error?
